# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "https://zaggurat-portfolio.netlify.app"

[_.globalMeta]
title = "Sheetal Naik | Frontend Developer Portfolio"
description = "Professional portfolio"
longDescription = "Zaggonaut is a retro-inspired theme for Astro, built using TypeScript, TailwindCSS, and Astro."
cardImage = "https://file.garden/aL51CH2cBBf7c9wl/portfolio-images/profile-image.png"
keywords = ["web development", "design", "technology"]

[_.blogMeta]
title = "Sheetal's Blog"
description = "Practical wisdom, unfiltered thoughts, and hot takes."
longDescription = "Web development, tech trends, and the occasional programming mishap."
cardImage = "https://file.garden/aL51CH2cBBf7c9wl/portfolio-images/profile-image.png"
keywords = ["web development", "design", "technology"]

[_.projectMeta]
title = "Sheetal's Projects"
description = "A list of my web development projects and developer tools."
longDescription = "All of my projects, including both frontend and full-stack applications."
cardImage = "https://file.garden/aL51CH2cBBf7c9wl/portfolio-images/profile-image.png"
keywords = ["web development", "design", "technology"]

[_.notFoundMeta]
title = "404 Not Found"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "https://file.garden/aL51CH2cBBf7c9wl/portfolio-images/profile-image.png"

[_.hero]
title = "Sheetal Naik"
subtitle = "Frontend / React Developer"
image = "https://file.garden/aL51CH2cBBf7c9wl/portfolio-images/profile-image.png"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "Sheetal Naik"
githubProfile = "https://github.com/sheet848"
twitterProfile = "https://twitter.com"
linkedinProfile = "https://linkedin.com/in/developer-sheetalnaik"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"
